- name: Upgrade all packages
  apt:
    name: '*'
    state: present

- name: Ensure {{ packages }} packages are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python3
    - python3-pip
  become: yes

- name: Ensure pip is up to date
  pip:
    name: pip
    extra_args: --upgrade
  become: yes