- name: Add docker’s official GPG key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Set up the stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Ensure Docker installed
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Ensure Docker service started
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Ensure setuptools Module for Python is installed
  pip:
    name: setuptools
  become: yes

- name: Ensure Docker Module for Python is installed
  pip:
    name: setuptools, docker, docker-compose
  become: yes